replicaCount: 1
image:
  repository: emirozbir/hello-world
  pullPolicy: IfNotPresent
  tag: 0.0.1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}

  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 5000
  applicationPort: 5000

ingress:
  enabled: true
  hosts:
    myhello.eltigre.online
  paths:
  annotations:
    kubernetes.io/ingress.class: nginx
  tls: false


resources:
  limits:
    cpu: 2048m
    memory: 1024Mi
  requests:
    cpu: 512m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}


hpa:
  enabled: true